nubis/cloudformation/main.json

Defaults the subnet to public when we create a jumphost

Default VPC subnetlocation to public

---

nubis/cloudformation/main.json
nubis/cloudformation/parameters.json-dist

Pin stack version

---

LICENSE

Add license file, fixes issue #10

---

.gitmodules

Submodule bump

---

nubis/cloudformation/main.json

ELBs can be omitted now.

---

nubis/cloudformation/main.json
nubis/cloudformation/parameters.json-dist

Defaults SubnetLocation public now and will fix issue #22

Remove Subnetlocation

---

nubis/bin/migrate
nubis/cloudformation/main.json

Add the ability to describe CloudFormation stacks.

---

nubis/cloudformation/parameters.json-dist

Rename KeyName to SSHKeyName

---

nubis/cloudformation/main.json

Use the proper lambda function

Use the proper lambda function

---

nubis/bin/migrate
nubis/cloudformation/main.json

If Consul doesn't have an EIP for us, peek at our CF Stack looking for an ElasticIP output

---

nubis/bin/migrate
nubis/cloudformation/main.json

Wait for cloudformation output so that we can get the EIP allocation ID

Fixed migrate script to wait for cloudformation output

---

nubis/cloudformation/parameters.json-dist

Version bump for parameters file

---

nubis/cloudformation/main.json

Fixed url for ec2 stack

---

ssh-keys.md

Added doc on how to add ssh keys

Docs update

---

nubis/cloudformation/main.json

Add StacksVersion to VPCinfo and MetaInfo

---

nubis/puppet/duo.pp
nubis/puppet/files/confd-fixup
nubis/puppet/files/duo.tmpl
nubis/puppet/files/duo.toml
nubis/puppet/init.pp

This will install and configure `duo_unix` using confd

Install and configure duo

---

nubis/cloudformation/main.json

Use the CredstashPolicy from the Meta stack to gain access to the platform consul ACL token

---

nubis/cloudformation/main.json

Fixes #63
Tested in nubis-lab/us-west-2

Set Purpose=Jumphost

---

nubis/builder/project.json

Onto v1.0.2-dev we go

---

nubis/builder/project.json
nubis/builder/provisioners.json
nubis/terraform/main.tf

Build for CentOS

---

nubis/bin/migrate
nubis/puppet/init.pp

Update to nubis-travis v1.0.3

---

nubis/terraform/main.tf

Disable EC2 Detailled monitoring

---

nubis/puppet/fail2ban.pp

Add and enable fail2ban on jumphosts

---

nubis/bin/migrate
nubis/terraform/main.tf

Get rid of NUBIS_MIGRATE

---

nubis/terraform/input.tf
nubis/terraform/main.tf

[discuss] Expose jumphost purpose

---

nubis/terraform/input.tf
nubis/terraform/main.tf

Remove redundant purpose

---

nubis/terraform/main.tf

Remove missed purpose tag

---

nubis/terraform/main.tf

Use nubis-terraform as the source for iamge search

---

nubis/puppet/fail2ban.pp
nubis/terraform/main.tf

Linting project
